### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by aclavin-eab** [Annikizzle/Bamazon#1]
Code looks good, let's try to start using let and const for our variables. It's a new javascript practice, introduced starting in 2016 and by now it's everywhere. It's a more semantic version of variable declaration that the industry is all leaning towards. If you need to be able to reassign a variable (x = new setting) after it's original declaration(var x = something) then you use let, otherwise you use const (let x = somethingThatWillBeReassigned, const x = somethingThatWontBeReAssigned)

**Comment by Annikizzle** [comment]
Gah--I forgot again. NOTE TAKEN! 👍
